### ISSUE TITLE
Login autonlp behind a proxy server

### ISSUE THREAD

**Issue by Nourdine-Dehri** [huggingface/autonlp#63]
Hello,

My account is **enabled for AutoNLP.**
I'm following the [page](https://github.com/huggingface/autonlp#readme)  to install autonlp on a **Windows 10**, **Python version 3.8.5**.

I tried the autonlp login via a terminal.

**Command :**
autonlp login --api-key *MY_HUGGING_FACE_API_TOKEN*

**Results:**

----------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\autonlp\utils.py", line 41, in http_get
    response = requests.get(
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/whoami-v2 (Caused by SSLError(SSLCertVerificationError(1, 'SSL: CERTIFICATE_VERIFY_FAILED certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<my-username>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<my-username>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<my-username>\Dev\huggingface\venv\Scripts\autonlp.exe\__main__.py", line 7, in <module>
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\autonlp\cli\autonlp.py", line 52, in main
    command.run()
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\autonlp\cli\login.py", line 31, in run
    client.login(token=self._api_key)
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\autonlp\autonlp.py", line 41, in login
    auth_resp = http_get(path="/whoami-v2", domain=config.HF_API, token=token, token_prefix="Bearer")
  File "c:\users\<my-username>\dev\huggingface\venv\lib\site-packages\autonlp\utils.py", line 45, in http_get
    raise UnreachableAPIError("❌ Failed to reach AutoNLP API, check your internet connection")
autonlp.utils.UnreachableAPIError: ❌ Failed to reach AutoNLP API, check your internet connection

----------------------------------------------------------------------------------------------------------------------------------------

Could you please tell me how to specify a proxy in the login command ?

Many thanks for your help on this,

++

**Comment by SBrandeis** [comment]
Hello @Nourdine-Dehri!
You should be able to use a proxy by setting the HTTP_PROXY or HTTPS_PROXY environment variables in your shell.

For example, if you are using Powershell:
```shell
$env:HTTP_PROXY="http://<PROXY_IP>:<PROXY_PORT"
autonlp login --api-key <API_TOKEN>
```

Let me know if this helps!

**Comment by Nourdine-Dehri** [comment]
Hello @SBrandeis 

Thank you for your help !

Adding the `HTTP_PROXY` and `HTTPS_PROXY` in my environment variables solved this issue.

![image](https://user-images.githubusercontent.com/83276589/116387721-5f37ae00-a81b-11eb-9ede-e185b40328f8.png)

++
