### ISSUE TITLE
TypeError: get_project() missing 1 required positional argument: 'is_eval' when uploading

### ISSUE THREAD

**Issue by suminb** [huggingface/autonlp#91]
When uploading a dataset, `upload.py` raises a `TypeError` stating that `get_project()` is missing `is_eval` argument.

```
$ autonlp upload --project sentiment_detection --split train \
               --col_mapping review:text,sentiment:target \
               --files ~/datasets/train.csv
> INFO    Uploading files for project: sentiment_detection
Traceback (most recent call last):
  File "/Users/sb/.pyenv/versions/test/bin/autonlp", line 8, in <module>
    sys.exit(main())
  File "/Users/sb/.pyenv/versions/test/lib/python3.9/site-packages/autonlp/cli/autonlp.py", line 54, in main
    command.run()
  File "/Users/sb/.pyenv/versions/test/lib/python3.9/site-packages/autonlp/cli/upload.py", line 82, in run
    project = client.get_project(name=self._name)
TypeError: get_project() missing 1 required positional argument: 'is_eval'
```

If I manually revise `upload.py` as follows

```
project = client.get_project(name=self._name, is_eval=False)
```

things work as they should. Likewise, this happens when trying to run the `train` command.

```
$ autonlp train --project sentiment_detection
> INFO    Starting Training For Project: sentiment_detection
Traceback (most recent call last):
  File "/Users/sb/.pyenv/versions/test/bin/autonlp", line 8, in <module>
    sys.exit(main())
  File "/Users/sb/.pyenv/versions/test/lib/python3.9/site-packages/autonlp/cli/autonlp.py", line 54, in main
    command.run()
  File "/Users/sb/.pyenv/versions/test/lib/python3.9/site-packages/autonlp/cli/train.py", line 34, in run
    project = client.get_project(name=self._name)
TypeError: get_project() missing 1 required positional argument: 'is_eval'
```

I'm using `autonlp` version 0.3.0.

```
$ autonlp --version
0.3.0
```

**Comment by SBrandeis** [comment]
Hi @suminb !
This is a bug introduced in `0.3.0`. We'll fix it as soon as possible.
Sorry for the inconvenience!

**Comment by suminb** [comment]
That was blazing fast! Thanks for the quick fix.
