### ISSUE TITLE
Auto NLP authentication issue

### ISSUE THREAD

**Issue by sudharsan2020** [huggingface/autonlp#98]
Login authentication fails while using the Hugging Face API token.

I tried authentication with the below command as per documentation, but getting the below error:
```autonlp login --api-key YOUR_HUGGING_FACE_API_TOKEN```

Error Trace:
```
> autonlp login --api-key YOUR_HUGGING_FACE_API_TOKEN
Traceback (most recent call last):
  File "/home/sudharsan/anaconda3/envs/auto/bin/autonlp", line 8, in <module>
    sys.exit(main())
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/autonlp/cli/autonlp.py", line 56, in main
    command.run()
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/autonlp/cli/login.py", line 31, in run
    client.login(token=self._api_key)
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/autonlp/autonlp.py", line 43, in login
    auth_resp = http_get(path="/whoami-v2", domain=config.HF_API, token=token, token_prefix="Bearer")
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/autonlp/utils.py", line 43, in http_get
    url=domain + path, headers=get_auth_headers(token=token, prefix=token_prefix), **kwargs
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/sudharsan/anaconda3/envs/auto/lib/python3.7/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'YOUR_HUGGING_FACE_API_TOKEN/whoami-v2': No schema supplied. Perhaps you meant http://YOUR_HUGGING_FACE_API_TOKEN/whoami-v2?
```
**Setup**:

- OS: Ubuntu 18.04 LTS
- Version of the Library used: **autonlp==0.3.4**
- Python version: **3.7**

Can anyone help to resolve the issue?

**Comment by abhishekkrthakur** [comment]
you need to replace `YOUR_HUGGING_FACE_API_TOKEN` with your own token from hf.co

**Comment by sudharsan2020** [comment]
Yes I've used the token from huggingface. I've replaced with placeholder since it's a public forum

**Comment by SBrandeis** [comment]
Hi @sudharsan2020 !

This might be an environment issue.
`autonlp` reads the `HF_API` environment variable, see [here](https://github.com/huggingface/autonlp/blob/main/src/autonlp/config.py#L9).
Most likely `HF_API` is set in your environment, causing issues when reaching the HuggingFace hub. Unsetting this environment variable should solve your issue.

Let us know if it helps ! 🤗

**Comment by sudharsan2020** [comment]
@SBrandeis This worked :clap: . The original key in my profile was overriding the configuration `HF_API`. Thanks :+1:
